/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tablafinal;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tablafinal.Mostrar;
/**
 *
 * @author r618b
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        BotonCrearTablas = new javax.swing.JButton();
        BotonInsertar = new javax.swing.JButton();
        BBorrar = new javax.swing.JButton();
        BModificar = new javax.swing.JButton();
        bMostrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaComp = new javax.swing.JTable();
        BConsulta = new javax.swing.JButton();
        ComboBox = new javax.swing.JComboBox<>();
        TConsulta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonCrearTablas.setText("Añadir tabla");
        BotonCrearTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearTablasActionPerformed(evt);
            }
        });

        BotonInsertar.setText("Insertar");
        BotonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInsertarActionPerformed(evt);
            }
        });

        BBorrar.setText("Borrar");
        BBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBorrarActionPerformed(evt);
            }
        });

        BModificar.setText("Modificar");
        BModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModificarActionPerformed(evt);
            }
        });

        bMostrar.setText("Mostrar");
        bMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMostrarActionPerformed(evt);
            }
        });

        tablaComp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "imei", "operadora"
            }
        ));
        jScrollPane2.setViewportView(tablaComp);

        BConsulta.setText("Consulta");
        BConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConsultaActionPerformed(evt);
            }
        });

        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "imei", "operadora", "marca" }));
        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });

        TConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                        .addContainerGap(132, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(BotonCrearTablas)
                                .addGap(18, 18, 18)
                                .addComponent(BotonInsertar)
                                .addGap(30, 30, 30))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TConsulta)
                            .addComponent(BBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(BModificar)
                                .addGap(28, 28, 28)
                                .addComponent(bMostrar)
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BConsulta)
                                .addGap(30, 30, 30))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCrearTablas)
                    .addComponent(BotonInsertar)
                    .addComponent(BBorrar)
                    .addComponent(BModificar)
                    .addComponent(bMostrar))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BConsulta)
                    .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCrearTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearTablasActionPerformed
   FromCrear obx=new FromCrear();
        obx.setVisible(true);
        this.setVisible(false);    }//GEN-LAST:event_BotonCrearTablasActionPerformed

    private void BotonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInsertarActionPerformed
insertar.insercion();    }//GEN-LAST:event_BotonInsertarActionPerformed

    private void BBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBorrarActionPerformed
Borrar.eliminar();
    }//GEN-LAST:event_BBorrarActionPerformed

    private void BModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModificarActionPerformed
        //Modificar.update2();
        Modificar app=new Modificar();
        long imei;
        String operadora;
        app.update(imei=Long.parseLong(JOptionPane.showInputDialog(null,"Introduce el imei para cambiar su operadora")), operadora=JOptionPane.showInputDialog(null,"Introduzca el nombre de la nueva operadora"));
        
    }//GEN-LAST:event_BModificarActionPerformed

    private void bMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMostrarActionPerformed


            try {                                         
                DefaultTableModel modelo =new DefaultTableModel();
                String tabla=JOptionPane.showInputDialog(null,"introduce el nombre de la tabla");
                ResultSet rs=Mostrar.getTabla("select * from "+tabla+"companhias");
                ResultSet rs2=Mostrar.getTabla("select * from "+tabla);
                modelo.setColumnIdentifiers(new Object[]{"imei","operadora"});
                try {
                    modelo.addColumn("marca");
                    while (rs.next()&& rs2.next()){
                        modelo.addRow(new Object[]{rs.getLong("imei"),rs.getString("operadora"),rs2.getString("marca")});
                    }
                    tablaComp.setModel(modelo);
                } catch (Exception e) {
                    System.out.println(e);
                }

                
//////////       ArrayList<Object[]> base=new ArrayList<>();
//////////        ArrayList<Object[]> base2=new ArrayList<>();
//////////        String tabla=JOptionPane.showInputDialog(null,"De que tabla desea mostrar los datos");
//////////        tablaMarca.setModel(Mostrar.blanco());
//////////        tablaComp.setModel(Mostrar.blanco2());
//////////        DefaultTableModel modelo =(DefaultTableModel) tablaMarca.getModel();
//////////        DefaultTableModel modelo2 =(DefaultTableModel) tablaComp.getModel();
//////////        base=Mostrar.selectT1(tabla);
//////////        base2=Mostrar.selectT2(tabla);
//////////        for(Object[] ele:base){
//////////            modelo.addRow(ele);
//////////        }
//////////
//////////        for(Object[] ele:base2){
//////////            modelo2.addRow(ele);
//////////        }
//////////        tablaMarca.setModel(modelo);
//////////        tablaComp.setModel(modelo2);

            } catch (SQLException ex) {
                Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null,ex);
            }
           
    
           
    
//////////       ArrayList<Object[]> base=new ArrayList<>();
//////////        ArrayList<Object[]> base2=new ArrayList<>();
//////////        String tabla=JOptionPane.showInputDialog(null,"De que tabla desea mostrar los datos");
//////////        tablaMarca.setModel(Mostrar.blanco());
//////////        tablaComp.setModel(Mostrar.blanco2());
//////////        DefaultTableModel modelo =(DefaultTableModel) tablaMarca.getModel();
//////////        DefaultTableModel modelo2 =(DefaultTableModel) tablaComp.getModel();
//////////        base=Mostrar.selectT1(tabla);
//////////        base2=Mostrar.selectT2(tabla);
//////////        for(Object[] ele:base){
//////////            modelo.addRow(ele);
//////////        }
//////////        
//////////        for(Object[] ele:base2){
//////////            modelo2.addRow(ele);
//////////        }
//////////        tablaMarca.setModel(modelo);
//////////        tablaComp.setModel(modelo2);
       
    }//GEN-LAST:event_bMostrarActionPerformed

    private void BConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConsultaActionPerformed
         try {                                         
                DefaultTableModel modelo =new DefaultTableModel();
                String condicion="";
                String tabla=JOptionPane.showInputDialog(null,"introduce el nombre de la tabla");
                if (ComboBox.getSelectedIndex()==0) {
                  condicion="imei";
             }
                else if(ComboBox.getSelectedIndex()==1){
                   condicion="operadora";
                }else
                    condicion="marca";
                ResultSet rs=Mostrar.getTabla("select * from "+tabla+"companhias where "+condicion+"= "+TConsulta.getText());
                System.out.println(condicion);
                ResultSet rs2=Mostrar.getTabla("select * from "+tabla+" where "+condicion+"= "+TConsulta.getText());
                modelo.setColumnIdentifiers(new Object[]{"imei","operadora","marca"});
                
                try {
                    modelo.addColumn("marca");
                   
                        modelo.addRow(new Object[]{rs.getLong("imei"),rs.getString("operadora"),rs2.getString("marca")});
                    
                    tablaComp.setModel(modelo);
                } catch (Exception e) {
                    System.out.println(e);
                }
 } catch (SQLException ex) {
                Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null,ex);
            }
           
        
    }//GEN-LAST:event_BConsultaActionPerformed

    private void TConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TConsultaActionPerformed

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBorrar;
    private javax.swing.JButton BConsulta;
    private javax.swing.JButton BModificar;
    private javax.swing.JButton BotonCrearTablas;
    private javax.swing.JButton BotonInsertar;
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JTextField TConsulta;
    private javax.swing.JButton bMostrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tablaComp;
    // End of variables declaration//GEN-END:variables
}
